language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- npm test
- ng e2e
- ng build --prod
deploy:
  skip_cleanup: true
  local_dir: dist/pesel
  provider: firebase
  token: $FIREBASE_TOKEN
  on:
    branch: master
